- hosts: vagrant
  vars:
   - docroot: /var/www/ansible-test/public
  tasks:
   - name: Add Nginx Repository
     apt_repository: repo='ppa:nginx/stable' state=present
     register: ppastable

   - name: Install Nginx
     apt: pkg=nginx state=installed update_cache=true
     when: ppastable|success
     register: nginxinstalled
     notify:
      - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started
   - name: Reload Nginx
     service: name=nginx state=reloaded
